
// Set the API key and YouTube video ID
const API_KEY = "AIzaSyDdpSg5bkAJvr53om-8AP_Z5hQl79PvfG4";
let VIDEO_ID = "YOUR_VIDEO_ID";
const urls = "https://www.youtube.com/watch?v=i53Gi_K3o7I&ab_channel=NeetCode"

var i, r, rx = /^.*(?:(?:youtu\.be\/|v\/|vi\/|u\/\w\/|embed\/|shorts\/)|(?:(?:watch)?\?v(?:i)?=|\&v(?:i)?=))([^#\&\?]*).*/;
    
r = urls.match(rx);
VIDEO_ID = r[1];


// Call the YouTube Data API to retrieve the video caption tracks
fetch(`https://www.googleapis.com/youtube/v3/captions?part=id%2Csnippet&videoId=${VIDEO_ID}&key=${API_KEY}`)
  .then(response => response.json())
  .then(captionTracks => {
    // Find the automatically generated caption track, if available
    const autoGeneratedTrack = captionTracks.items.find(track => track.snippet.isAutoSynced);
    const autoGeneratedTrackId = autoGeneratedTrack ? autoGeneratedTrack.id : null;

    // Call the YouTube Data API to retrieve the transcript of the auto-generated caption track
    if (autoGeneratedTrackId) {
      fetch(`https://www.googleapis.com/youtube/v3/captions/${autoGeneratedTrackId}?tfmt=srt&key=${API_KEY}`)
        .then(response => response.text())
        .then(transcript => {
          // Print the transcript text
          console.log(transcript);
        })
        .catch(error => console.error(`An error occurred: ${error}`));
    }
  })
  .catch(error => console.error(`An error occurred: ${error}`));
